"""initial

Revision ID: 683a08df4c88
Revises: 
Create Date: 2026-01-30 23:13:52.923038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683a08df4c88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stamps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('scott_number', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('expired_date', sa.DateTime(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.Column('designers', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('emission', sa.String(), nullable=True),
    sa.Column('paper', sa.String(), nullable=True),
    sa.Column('gum', sa.String(), nullable=True),
    sa.Column('perforation', sa.String(), nullable=True),
    sa.Column('printing', sa.String(), nullable=True),
    sa.Column('face_value', sa.String(), nullable=True),
    sa.Column('print_run', sa.Integer(), nullable=True),
    sa.Column('watermark', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added_to_db', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scott_number', 'country', name='uq_scott_country')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stamp_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stamp_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['stamp_id'], ['stamps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stamp_theme_association',
    sa.Column('stamp_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stamp_id'], ['stamps.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('stamp_id', 'theme_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stamp_theme_association')
    op.drop_table('stamp_images')
    op.drop_table('themes')
    op.drop_table('stamps')
    # ### end Alembic commands ###
