"""add variants col

Revision ID: 796f688b4fcf
Revises: d78224606901
Create Date: 2026-01-31 20:16:34.680223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796f688b4fcf'
down_revision: Union[str, Sequence[str], None] = 'd78224606901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stamps', sa.Column('variants', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stamps', 'variants')
    # ### end Alembic commands ###
